opt_in_rules:
    - anyobject_protocol
    - attributes
    - block_based_kvo
    - closure_body_length
    - closure_end_indentation
    - closure_spacing
    - collection_alignment
    - contains_over_first_not_nil
    - convenience_type
    - discarded_notification_center_observer
    - discouraged_optional_boolean
    - empty_count
    - empty_string
    - empty_xctest_method
    - explicit_init
    - extension_access_modifier
    - fallthrough
    - fatal_error_message
    - file_header
    - file_name
    - file_types_order
    - first_where
    - for_where
    - force_try
    - force_unwrapping
    - function_default_parameter_at_end
    - function_parameter_count
    - identical_operands
    - implicit_return
    - joined_default_parameter
    - last_where
    - legacy_random
    - let_var_whitespace
    - literal_expression_end_indentation
    - lower_acl_than_parent
    # - missing_docs
    - modifier_order
    - multiline_arguments
    - multiline_function_chains	
    - multiline_literal_brackets
    - multiline_parameters
    - number_separator
    - operator_usage_whitespace
    - operator_whitespace
    - overridden_super_call
    - override_in_extension
    - pattern_matching_keywords
    - reduce_into
    - redundant_nil_coalescing
    - redundant_type_annotation
    - required_enum_case
    - sorted_first_last
    - sorted_imports
    - static_operator
    - strong_iboutlet
    - toggle_bool
    - trailing_closure
    - type_contents_order
    - unavailable_function
    - unneeded_parentheses_in_closure_argument
    - untyped_error_in_catch
    - unused_import
    - unused_private_declaration
    - vertical_parameter_alignment_on_call
    - vertical_whitespace_between_cases
    - vertical_whitespace_closing_braces
    - yoda_condition

excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Pods
    - Carthage

disabled_rules:
    - todo